config/routes.rb
Rails.application.routes.draw do

    get '/messages', to: 'messages#index'
    root to: 'pages#home'
    resources :posts
    resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    include Sluggable
    validates :name, presence: true
    validates :slug, format: { with: /\A[a-z0-9\-]+\z/ }, uniqueness: true

    has_many :posts
    has_many :metas, as: :metaable
end

app/models/concerns/sluggable.rb
module Sluggable
    extend ActiveSupport::Concern

    included do
        before_validation :set_default_slug, on: [:create, :update], if: '!slug.nil?'


        private
        def set_default_slug
            if !self.name.nil? && !self.name.empty? && self.slug.empty?
                self.slug = name.parameterize
            end
        end
    end
end

app/models/meta.rb
class Meta < ApplicationRecord

    belongs_to :metaable, polymorphic: true

end

app/models/post.rb
class Post < ApplicationRecord

    include Sluggable

    belongs_to :category, counter_cache: true
    has_and_belongs_to_many :tags
    has_many :metas, as: :metaable

    default_scope {order(created_at: :desc)} #sera executé partout

    scope :online, -> (online) do
        where(online: online) if online.is_a? Integer
    end

    scope :offline, -> {where(online: 0)}

    scope :alpha, -> { order(name: :asc)}

    validates :name, presence: true
    validates :slug, format: { with: /\A[a-z0-9\-]+\z/ }, uniqueness: true


end

app/models/tag.rb
class Tag < ApplicationRecord

    has_and_belongs_to_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    add_flash_types :success, :danger
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :set_categories, only: [:update, :edit, :show, :destroy]


    def index
        @session = session[:user_id]
        @categories = Category.all
          respond_to do |format|
            format.html
            format.json { render json: @categories }
        end
    end

    def show
    end

    def update
        @category.update(category_params)
        redirect_to category_path(@category.id), success: "Catégorie modifiée avec succès"
    end
    def new
        @category = Category.new
    end

    def edit
    end

    def create
        @category = Category.create(category_params)
        redirect_to categories_path, success: "Catégorie créée avec succès"
    end
    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to categories_path, success: "Catégorie supprimée avec succès"
    end

    private
    def category_params
        params.require(:category).permit(:name, :slug)
    end

    def set_categories
        @category = Category.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def index
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        #ContactMailer.contact(Post.first).deliver_later
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


    before_action :set_posts, only: [:update, :edit, :show, :destroy]

    def index
        #flash.now[:success] = "Salut" --affiche un message flash sur la session en cours uniquement (ex : alerte promotion)
        @posts = Post.online(1).alpha.includes(:category, :tags).all

        #@posts = Post.published(0).alpha.rewhere(online: 0).all --écrase le scope published pour afficher les offline

        respond_to do |format|
            format.html
            format.json { render json: @posts.as_json(only: [:name, :created_at, :id]) }
        end

    end

    def show
    end

    def edit
    end

    def update
        if @post.update(post_params)
            redirect_to posts_path, success: "Article modifié avec succès"
        else
            render 'edit'
        end
    end

    def new
        @post = Post.new
    end

    def create
        post = Post.create(post_params)
        redirect_to post_path(post.id), success: "Article créé avec succès"
    end

    def destroy
        @post.destroy
        redirect_to posts_path, success: "Article supprimé avec succès"
    end

    private
    def post_params
        params.require(:post).permit(:name, :content, :slug, :category_id)
    end

    def set_posts
        @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gravatar_helper.rb
module GravatarHelper

    def gravatar(email, options = {s: 200})
        throw TypeError unless email.respond_to?(:to_s)
        image_tag "https://fr.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.to_s)}?s=#{options[:s]}"
    end
end

app/views/categories/edit.html.erb
<h1>Editer la catégorie</h1>

<% if @category.errors.any? %>
<div class="alert alert-danger">
    <% @category.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
</div>
<% end %>

<%= form_for @category do |f| %>
<div class="form-group">
    <%= f.text_field :name, placeholder: 'Nom', class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.text_field :slug, placeholder: 'Url', class: 'form-control' %>
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary">Modifier la catégorie</button>
</div>
<% end %>

app/views/categories/index.html.erb
<h1>Les catégories</h1>

<!--
<p>
    Session : <%= @session.inspect %>
</p>
-->

<table class="table">
    <thead>
        <tr>
            <td>ID</td>
            <td>Nom</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
    <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td>
        <a href="<%= edit_category_path(category.id)%>" class="btn btn-primary">Editer</a>
        <a href="<%= category_path(category.id)%>" class="btn btn-danger" data-confirm="sur ?" data-method="DELETE">Supprimer</a>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>

<p>
    <a href="<%= new_category_path %>" class="btn btn-success">Créer une nouvelle catégorie</a>
</p>

app/views/categories/new.html.erb
<h1>Nouvelle catégorie</h1>

<%= form_for @category do |f| %>
<div class="form-group">
    <%= f.text_field :name, placeholder: 'Nom', class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.text_field :slug, placeholder: 'Url', class: 'form-control' %>
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary">Créer la catégorie</button>
</div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p><%= @category.slug %></p>


<p>
    <a href="<%= categories_path%>" class="btn btn-primary">Revenir aux catégories</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'Ruby On Rails Démo' %></title>
    <%= csrf_meta_tags %>

    <!-- test pour le chat -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<!-- Commentaires tests scss
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
-->

  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
      <a class="navbar-brand" href="<%= root_path %>">Ruby on Rails</a>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<%= posts_path %>">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= categories_path %>">Catégories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= messages_path %>">Chat - ActionCables</a>
        </li>
      </ul>
    </nav>

    <div class="container" style="padding-top: 5rem;">

        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name %>"><%= msg %></div>
        <% end %>

        <%= yield %>


    </div><!-- /.container -->



  </body>
</html>

app/views/layouts/sidebar.html.erb
<div class="row">
    <div class="col-sm-8">
        <%= yield(:content) %>
    </div>
    <div class="col-sm-4">
        <%= yield(:sidebar) %>
    </div>
</div>

app/views/messages/_message.html.erb
<div class="comment">

    <div class="content">
        <%= message %>
    </div>

</div>

app/views/messages/index.html.erb
<div class="ui container">

    <ul id="messages" class="ui comments">


    </ul>

    <div class="ui rply form">

        <div class="field">
            <textarea id="message" placeholder="Votre message"></textarea>
        </div>

    </div>
</div>

app/views/pages/home.html.erb
<h1>Bienvenue sur mon exemple Ruby On Rails</h1>


<p>Ce site permet de voir et comprendre le fonctionnement de Ruby on Rails de façon simple.</p>
<p>Il a été élaboré à partir de 0 en suivant différents tutoriel dont ceux de Grafikart.</p>
<p>Un container a également été mis en place pour pouvoir tester les différents cas et configuaration de façon simple et sans impacter la configuration de votre machine.</p>

<p>Merci et bonne lecture.</p>

<%= image_tag 'rubyonrails-logo.png', width: 100 %>

app/views/posts/_form.html.erb
<% if item.errors.any? %>
<div class="alert alert-danger">
    <% item.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
</div>
<% end %>

<%= form_for item do |f| %>

    <div class="form-group">
        <label>Titre de l'article</label>
        <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Url de l'article</label>
        <%= f.text_field :slug, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Catégorie de l'article</label>
        <%= f.select :category_id, Category.pluck(:name, :id), class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Contenu de l'article</label>
        <%= f.text_area :content, class: 'form-control' %>
    </div>
<div class="form-group"><button type="submit" class="btn btn-primary">Modifier l'article</button></div>
<% end %>

app/views/posts/_post.html.erb
    <h2><%= post.name %></h2>

    <p><%= post.content %></p>

    <% if post.category %>
        <p>Catégorie : <%= post.category.name %></p>
    <% end %>

    <% if !post.tags.empty? %>
        <p>Tags :
            <%= post.tags.map(&:name).join(', ') %>
        </p>
    <% end %>

    <p>
       <%= link_to('Lire la suite', post, class: 'btn btn-primary') %>
       <%= link_to('Edit', [:edit, post], class: 'btn btn-warning') %>
       <%= link_to('Supprimer', post, class: 'btn btn-danger', data: {confirm: 'êtes-vous sur ?', method: :delete}) %>
    </p>

app/views/posts/edit.html.erb
<h1>Editer l'article</h1>

<%= url_for(controller: 'posts', action: 'index', host: 'localhost.dev', port: 80) %>

<%= gravatar('boucheau.tony@neuf.fr'); %>

<%= render 'form', item: @post %>

app/views/posts/index.html.erb
<h1>Articles</h1>


<%= render @posts %>


<p>
    <a href="<%= new_post_path %>" class="btn btn-success">Créer un article</a>
</p>

app/views/posts/new.html.erb
<h1>Créer un article</h1>


<%= render 'form', item: @post %>

app/views/posts/show.html.erb
<% content_for(:title, @post.name) %>

<% content_for :content do %>
<h1><%= @post.name %></h1>

<p><%= @post.content%></p>


<p>
    <a href="<%= posts_path%>" class="btn btn-primary">Revenir aux articles</a>
</p>


<% end %>

<% content_for :sidebar do %>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, veritatis, accusantium. Aperiam officia eum reiciendis dolor. Nesciunt dolores laudantium mollitia laboriosam deleniti architecto adipisci voluptas fugit, nulla enim! Quaerat, deleniti.
<% end %>



<%= render template: 'layouts/sidebar' %>